FROM python:3.9

WORKDIR /app

COPY ./services/backend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY ./services/backend /app

CMD ["python", "app.py"]